### PR TITLE
Allow User to Specify Install and Build Folders

### PR DESCRIPTION
**Pull request by MichelleHetzel**

### CODE REVIEW

**Comment by stefaneicher** [comment]
Thanks Michelle for the PR. We are honored that you joined Github to create your first repo and PR ever for our project. Welcome on Github!
We will review it if we find time in the next days.
Regards Stefan

**Comment by MichelleHetzel** [comment]
Thanks! I’m not super new to github, my company just requires me to contribute to open source projects using my corporate email.  Thanks for taking a look! My team is excited to have stronger conan integration with vscode.
-Michelle

**Comment by mymichu** [comment]
Hi Michelle this is a great improvement thank you for your contribution. It totally makes sense to integrate this into the conan vs-code plugin. I will release it in the store by today, under the version 0.6.0.

**Comment by MichelleHetzel** [comment]
> Hi Michelle this is a great improvement thank you for your contribution. It totally makes sense to integrate this into the conan vs-code plugin. I will release it in the store by today, under the version 0.6.0.

Thank you! This was for the [issue](https://github.com/disroop/vs-code-conan/issues/13) I raised a while back 😄

**Pull request merged**
